project:
  title: "bestageing2025"
  execute-dir: project
  output-dir: quarto_output
  render:
    - "*.qmd"
    - "!ignored.qmd"
    - "!ignored-dir/"

toc: true
number-sections: true
bibliography: references.bib

format:
  html:
    theme: cosmo
    embed-resources: true
    fontsize: 1em
    linestretch: 1.5
    comments:
      hypothesis: true

  pdf:
    echo: false

execute:
  freeze: false


